 # Stand up not-carousel for testing against.
version: "3"
services:
  modbus:
    container_name: modbus
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "1502:1502"
